CREATE TABLE user_details(
	ID INT PRIMARY KEY NOT NULL,
	NAME CHAR(50) NOT NULL,
	EMAIL CHAR(255) NOT NULL,
	PASSWORD CHAR(1000) NOT NULL,
	AGE INT NOT NULL,
	SPORTS CHAR(50) NOT NULL
);

INSERT INTO user_details (ID, NAME, EMAIL, PASSWORD, AGE, SPORTS) VALUES(1, 'ram', 'ram@ram.com', 'ram', 23, 'cricket');